### PR TITLE
Support discord.py 1.7, add ctx.typing() and fix a couple commands

### PR DESCRIPTION
**Pull request by CircuitSacul**
I made the commit messages as descriptive as possible, but here's what I changed:

1. change bot.owner_id to bot.config_owner_id
This is because bot.owner_id is used by commands.Bot by default, so when init() is called it get's overwritten. If in a team, owner_id is None and then commands like bug and improvement fail to work

2. Show user id even if the user is unknown in `list_blacklist`

3. Add ctx.typing() to `code` command.
It's helpful to know that the bot is working, since the fetch to wandbox takes a few seconds.

4. Add `commands.Cog` to cogs class
Discord.py requires that cogs subclass commands.Cog, so newer version will fail to run without this

5. Update requirements.txt and use version numbers
This way if a library releases a breaking change, discode will still run without a problem.

I tested this with discord.py 1.7 and python3.9

### CODE REVIEW

**Comment by OldBeafantles** [comment]
Nice PR, can you just add changes to the beautify scripts? As we've discussed on Discord (`yapf -ir --style google .`)

**Comment by CircuitSacul** [comment]
Done.

**Comment by OldBeafantles** [comment]
Nice, I think you just forgot the letter `y` for `yapf` in the scripts :p

**Comment by OldBeafantles** [comment]
Otherwise, it's perfect.

**Comment by CircuitSacul** [comment]
Fixed lol

**Comment by OldBeafantles** [comment]
Nice, thank you very much Circuit :)

**Pull request merged**
